// src/js/main/main.tsx
import { useEffect, useState } from "react";
import { FaBolt, FaNodeJs, FaAdobe } from "react-icons/fa";
import { os, path } from "../lib/node";
import { csi, evalES, evalFile, openLinkInBrowser } from "../lib/utils";

import logo from "../logo.svg";

import "./main.scss";

const Main = () => {
  const [count, setCount] = useState(0);

  const jsxTest = () => {
    console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
  };

  const nodeTest = () => {
    alert(
      `Node.js ${process.version}\nPlatform: ${
        os.platform
      }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
    );
  };

  useEffect(() => {
    if (window.cep) {
      console.log(`${csi.getSystemPath("extension")}/jsx/index.js`);
      evalFile(`${csi.getSystemPath("extension")}/jsx/index.js`).then(() => {});
    }
  }, []);

  return (
    <div className="app">
      <header className="app-header">
        <img src={logo} className="app-logo" alt="logo" />
        <h1>Bolt CEP</h1>
        <FaBolt />
        <p>Vite + React + TypeScript + Scss</p>
        <div className="button-group">
          <button onClick={() => setCount((count) => count + 1)}>
            Count is: {count}
          </button>
          <button onClick={nodeTest}>
            <FaNodeJs />
          </button>
          <button onClick={jsxTest}>
            <FaAdobe />
          </button>
        </div>
        <p>
          Edit <code>app.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <button
            className="app-link"
            onClick={() => openLinkInBrowser("https://reactjs.org")}
          >
            Learn React
          </button>
          {" | "}
          <button
            className="app-link"
            onClick={() =>
              openLinkInBrowser("https://vitejs.dev/guide/features.html")
            }
          >
            Vite Docs
          </button>
        </p>
      </header>
    </div>
  );
};

export default Main;

// templates/vue/main/main.vue
<script setup lang="ts">
import path from "path";
import { ref } from "vue";
import { os } from "../lib/node";
import { csi, evalES, openLinkInBrowser } from "../lib/utils";
import "../index.scss";

const count = ref(0);

const jsxTest = () => {
  console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
};

const nodeTest = () => {
  alert(
    `Node.js ${process.version}\nPlatform: ${
      os.platform
    }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
  );
};
</script>

<template>
  <div className="app">
    <header className="app-header">
      <img className="app-logo" alt="Vue logo" src="./vue-logo.png" />
      <h1>Bolt CEP</h1>
      <img className="icon" src="../assets/bolt.svg" />
      <p>Vite + Vue + TypeScript + Scss</p>
      <div className="button-group">
        <button @click="count++">Count is: {{ count }}</button>
        <button @click="nodeTest">
          <img className="icon-button" src="../assets/node-js.svg" />
        </button>
        <button @click="jsxTest">
          <img className="icon-button" src="../assets/adobe.svg" />
        </button>
      </div>

      <p>Edit <code>app.vue</code> and save to test HMR updates.</p>
      <p>
        <button @click="() => openLinkInBrowser('https://v3.vuejs.org/')">
          Vue Docs
        </button>
        |
        <button
          @click="
            () => openLinkInBrowser('https://vitejs.dev/guide/features.html')
          "
        >
          Vite Docs
        </button>
      </p>
    </header>
  </div>
</template>
