// src/js/main/main.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { os, path } from "../lib/cep/node";
  import {
    csi,
    evalES,
    openLinkInBrowser,
    subscribeBackgroundColor,
    evalTS,
  } from "../lib/utils/bolt";
  import "../index.scss";
  import "./main.scss";
  let backgroundColor: string = "#282c34";

  // BOLT_SAMPLECODE_START
  import viteLogo from "../assets/vite.svg";
  import svelteLogo from "../assets/svelte.svg";
  import tsLogo from "../assets/typescript.svg";
  import sassLogo from "../assets/sass.svg";
  import nodeJs from "../assets/node-js.svg";
  import adobe from "../assets/adobe.svg";
  import bolt from "../assets/bolt-cep.svg";

  let count: number = 0;

  //* Demonstration of Traditional string eval-based ExtendScript Interaction
  const jsxTest = () => {
    console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
  };

  //* Demonstration of End-to-End Type-safe ExtendScript Interaction
  const jsxTestTS = () => {
    evalTS("helloStr", "test").then((res) => {
      console.log(res);
    });
    evalTS("helloNum", 1000).then((res) => {
      console.log(typeof res, res);
    });
    evalTS("helloArrayStr", ["ddddd", "aaaaaa", "zzzzzzz"]).then((res) => {
      console.log(typeof res, res);
    });
    evalTS("helloObj", { height: 90, width: 100 }).then((res) => {
      console.log(typeof res, res);
      console.log(res.x);
      console.log(res.y);
    });
    evalTS("helloVoid").then(() => {
      console.log("function returning void complete");
    });
    evalTS("helloError", "test").catch((e) => {
      console.log("there was an error", e);
    });
  };

  const nodeTest = () => {
    alert(
      `Node.js ${process.version}\nPlatform: ${
        os.platform
      }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
    );
  };
  // BOLT_SAMPLECODE_END

  onMount(() => {
    if (window.cep) {
      subscribeBackgroundColor((c: string) => (backgroundColor = c));
    }
  });
</script>

<div class="app" style="background-color: {backgroundColor};">
  <header class="app-header">
    <!-- BOLT_SAMPLECODE_START -->
    <img src={bolt} class="icon" alt="" />
    <div class="stack-icons">
      <div>
        <img src={viteLogo} alt="" />
        Vite
      </div>
      +
      <div>
        <img src={svelteLogo} alt="" />
        Svelte
      </div>
      +
      <div>
        <img src={tsLogo} alt="" />
        TypeScript
      </div>
      +
      <div>
        <img src={sassLogo} alt="" />
        Sass
      </div>
    </div>
    <div class="button-group">
      <button on:click={() => (count += 1)}>Count is: {count}</button>
      <button on:click={nodeTest}>
        <img class="icon-button" src={nodeJs} alt="" />
      </button>
      <button on:click={jsxTest}>
        <img class="icon-button" src={adobe} alt="" />
      </button>
      <button on:click={jsxTestTS}>Ts</button>
    </div>

    <p>Edit <code>main.svelte</code> and save to test HMR updates.</p>
    <p>
      <button
        on:click={() =>
          openLinkInBrowser("https://github.com/hyperbrew/bolt-cep")}
      >
        Bolt Docs
      </button>
      |
      <button on:click={() => openLinkInBrowser("https://svelte.dev/docs")}>
        Svelte Docs
      </button>
      |
      <button
        on:click={() =>
          openLinkInBrowser("https://vitejs.dev/guide/features.html")}
      >
        Vite Docs
      </button>
    </p>
    <!-- BOLT_SAMPLECODE_END -->
  </header>
</div>

<style lang="scss">
  @use "../variables.scss" as *;
</style>

// src/js/main/main.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { os, path } from "../lib/cep/node";
import {
  csi,
  evalES,
  openLinkInBrowser,
  subscribeBackgroundColor,
  evalTS,
} from "../lib/utils/bolt";
import "../index.scss";

const backgroundColor = ref("#282c34");

// BOLT_SAMPLECODE_START
const count = ref(0);

//* Demonstration of Traditional string eval-based ExtendScript Interaction
const jsxTest = () => {
  console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
};

//* Demonstration of End-to-End Type-safe ExtendScript Interaction
const jsxTestTS = () => {
  evalTS("helloStr", "test").then((res) => {
    console.log(res);
  });
  evalTS("helloNum", 1000).then((res) => {
    console.log(typeof res, res);
  });
  evalTS("helloArrayStr", ["ddddd", "aaaaaa", "zzzzzzz"]).then((res) => {
    console.log(typeof res, res);
  });
  evalTS("helloObj", { height: 90, width: 100 }).then((res) => {
    console.log(typeof res, res);
    console.log(res.x);
    console.log(res.y);
  });
  evalTS("helloVoid").then(() => {
    console.log("function returning void complete");
  });
  evalTS("helloError", "test").catch((e) => {
    console.log("there was an error", e);
  });
};

const nodeTest = () => {
  alert(
    `Node.js ${process.version}\nPlatform: ${
      os.platform
    }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
  );
};
// BOLT_SAMPLECODE_END

onMounted(() => {
  if (window.cep) {
    subscribeBackgroundColor((c: string) => (backgroundColor.value = c));
  }
});
</script>

<template>
  <div class="app" :style="{ backgroundColor: backgroundColor }">
    <header class="app-header">
      <!-- BOLT_SAMPLECODE_START -->
      <img src="../assets/bolt-cep.svg" class="icon" />
      <div class="stack-icons">
        <div>
          <img src="../assets/vite.svg" />
          Vite
        </div>
        +
        <div>
          <img src="../assets/vue.svg" />
          Vue
        </div>
        +
        <div>
          <img src="../assets/typescript.svg" />
          TypeScript
        </div>
        +
        <div>
          <img src="../assets/sass.svg" />
          Sass
        </div>
      </div>
      <div class="button-group">
        <button @click="count++">Count is: {{ count }}</button>
        <button @click="nodeTest">
          <img class="icon-button" src="../assets/node-js.svg" />
        </button>
        <button @click="jsxTest">
          <img class="icon-button" src="../assets/adobe.svg" />
        </button>
        <button @click="jsxTestTS">Ts</button>
      </div>

      <p>Edit <code>main.vue</code> and save to test HMR updates.</p>
      <p>
        <button
          @click="
            () => openLinkInBrowser('https://github.com/hyperbrew/bolt-cep')
          "
        >
          Bolt Docs
        </button>
        |
        <button @click="() => openLinkInBrowser('https://v3.vuejs.org/')">
          Vue Docs
        </button>
        |
        <button
          @click="
            () => openLinkInBrowser('https://vitejs.dev/guide/features.html')
          "
        >
          Vite Docs
        </button>
      </p>
      <!-- BOLT_SAMPLECODE_END -->
    </header>
  </div>
</template>

<style lang="scss">
@use "../variables.scss" as *;
</style>
