// src/js/template-svelte/main.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { fs, os, path } from "../lib/node";
  import { csi, evalFunction, evalFile, openLinkInBrowser } from "../lib/utils";

  import viteLogo from "../assets/vite.svg";
  import svelteLogo from "../assets/svelte.svg";
  import tsLogo from "../assets/typescript.svg";
  import sassLogo from "../assets/sass.svg";

  import nodeJs from "../assets/node-js.svg";
  import adobe from "../assets/adobe.svg";
  import bolt from "../assets/bolt-cep.svg";

  import "../index.scss";
  import "./main.scss";

  let count = 0;

  const jsxTest = () => {
    console.log(evalFunction('helloWorld', csi.getApplicationID()));
  };

  const nodeTest = () => {
    alert(
      `Node.js ${process.version}\nPlatform: ${
        os.platform
      }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
    );
  };

  onMount(() => {
    if (window.cep) {
      const extRoot = csi.getSystemPath("extension");
      const jsxSrc = `${extRoot}/jsx/index.js`;
      const jsxBinSrc = `${extRoot}/jsx/index.jsxbin`;
      if (fs.existsSync(jsxSrc)) {
        console.log(jsxSrc);
        evalFile(jsxSrc);
      } else if (fs.existsSync(jsxBinSrc)) {
        console.log(jsxBinSrc);
        evalFile(jsxBinSrc);
      }
    }
  });
</script>

<div class="app">
  <header class="app-header">
    <img src={bolt} class="icon" alt="" />
    <div class="stack-icons">
      <div>
        <img src={viteLogo} alt="" />
        Vite
      </div>
      +
      <div>
        <img src={svelteLogo} alt="" />
        Svelte
      </div>
      +
      <div>
        <img src={tsLogo} alt="" />
        TypeScript
      </div>
      +
      <div>
        <img src={sassLogo} alt="" />
        Sass
      </div>
    </div>
    <div class="button-group">
      <button on:click={() => (count += 1)}>Count is: {count}</button>
      <button on:click={nodeTest}>
        <img class="icon-button" src={nodeJs} alt="" />
      </button>
      <button on:click={jsxTest}>
        <img class="icon-button" src={adobe} alt="" />
      </button>
    </div>

    <p>Edit <code>main.svelte</code> and save to test HMR updates.</p>
    <p>
      <button
        on:click={() =>
          openLinkInBrowser("https://github.com/hyperbrew/bolt-cep")}
      >
        Bolt Docs
      </button>
      |
      <button on:click={() => openLinkInBrowser("https://svelte.dev/docs")}>
        Svelte Docs
      </button>
      |
      <button
        on:click={() =>
          openLinkInBrowser("https://vitejs.dev/guide/features.html")}
      >
        Vite Docs
      </button>
    </p>
  </header>
</div>

<style>
</style>

// src/js/template-react/main.tsx
import { useEffect, useState } from "react";
import { os, path, fs } from "../lib/node";
import { csi, evalFunction, evalFile, openLinkInBrowser } from "../lib/utils";

import reactLogo from "../assets/react.svg";
import viteLogo from "../assets/vite.svg";
import tsLogo from "../assets/typescript.svg";
import sassLogo from "../assets/sass.svg";

import nodeJs from "../assets/node-js.svg";
import adobe from "../assets/adobe.svg";
import bolt from "../assets/bolt-cep.svg";

import "./main.scss";

const Main = () => {
  const [count, setCount] = useState(0);

  const jsxTest = () => {
    console.log(evalFunction("helloWorld", csi.getApplicationID()));
  };

  const nodeTest = () => {
    alert(
      `Node.js ${process.version}\nPlatform: ${
        os.platform
      }\nFolder: ${path.basename(window.cep_node.global.__dirname)}`
    );
  };

  useEffect(() => {
    if (window.cep) {
      const extRoot = csi.getSystemPath("extension");
      const jsxSrc = `${extRoot}/jsx/index.js`;
      const jsxBinSrc = `${extRoot}/jsx/index.jsxbin`;
      if (fs.existsSync(jsxSrc)) {
        console.log(jsxSrc);
        evalFile(jsxSrc);
      } else if (fs.existsSync(jsxBinSrc)) {
        console.log(jsxBinSrc);
        evalFile(jsxBinSrc);
      }
    }
  }, []);

  return (
    <div className="app">
      <header className="app-header">
        <img src={bolt} className="icon" />
        <div className="stack-icons">
          <div>
            <img src={viteLogo} />
            Vite
          </div>
          +
          <div>
            <img src={reactLogo} />
            React
          </div>
          +
          <div>
            <img src={tsLogo} />
            TypeScript
          </div>
          +
          <div>
            <img src={sassLogo} />
            Sass
          </div>
        </div>
        <div className="button-group">
          <button onClick={() => setCount((count) => count + 1)}>
            Count is: {count}
          </button>
          <button onClick={nodeTest}>
            <img className="icon-button" src={nodeJs} />
          </button>
          <button onClick={jsxTest}>
            <img className="icon-button" src={adobe} />
          </button>
        </div>
        <p>
          Edit <code>main.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <button
            className="app-link"
            onClick={() =>
              openLinkInBrowser("https://github.com/hyperbrew/bolt-cep")
            }
          >
            Bolt Docs
          </button>
          {" | "}
          <button
            className="app-link"
            onClick={() => openLinkInBrowser("https://reactjs.org")}
          >
            React Docs
          </button>
          {" | "}
          <button
            className="app-link"
            onClick={() =>
              openLinkInBrowser("https://vitejs.dev/guide/features.html")
            }
          >
            Vite Docs
          </button>
        </p>
      </header>
    </div>
  );
};

export default Main;
